import React, { useState, useEffect } from "react";
import {
  Volume2,
  CheckCircle,
  XCircle,
  Sparkles,
  ArrowRight,
  ArrowLeft,
  BookOpen,
  Award,
  RotateCcw,
  Check,
  Star,
  Lock,
  Unlock,
  Smile,
  Globe2,
  Languages,
  Layers,
  Plane,
  Building2,
  Utensils,
  Train,
  ShoppingBag,
  Landmark,
  Mic,
  Loader2,
  Wand2,
  PlusCircle,
  RefreshCw,
} from "lucide-react";
import confetti from "canvas-confetti";
import { LessonData, VocabWord, UserProfile } from "../types";
import { speakText, playChime } from "../utils/audio";
import { getLanguageMeta, MODULE_DEFINITIONS } from "../data/multilingualData";
import { PronunciationCheckModal } from "./PronunciationCheckModal";
import { generateAILesson } from "../services/aiService";

interface Props {
  lesson: LessonData;
  user?: UserProfile;
  selectedModuleId?: string;
  onSelectModule?: (moduleId: string) => void;
  onCompleteLesson: (xpReward: number) => void;
  onGoToDashboard: () => void;
}

export const LearnModuleView: React.FC<Props> = ({
  lesson,
  user,
  selectedModuleId = "airport",
  onSelectModule,
  onCompleteLesson,
  onGoToDashboard,
}) => {
  const [activeLesson, setActiveLesson] = useState<LessonData>(lesson);
  const [isAIGenerated, setIsAIGenerated] = useState<boolean>(false);
  const [isGeneratingAI, setIsGeneratingAI] = useState<boolean>(false);
  const [generationNotice, setGenerationNotice] = useState<string | null>(null);
  const [showCustomModal, setShowCustomModal] = useState<boolean>(false);
  const [customTopicInput, setCustomTopicInput] = useState<string>("");

  const [currentStep, setCurrentStep] = useState<number>(1);
  const [activeVocabIndex, setActiveVocabIndex] = useState<number>(0);
  const [showHindi, setShowHindi] = useState<boolean>(true);

  // Sync with incoming lesson if user switches module via prop
  useEffect(() => {
    setActiveLesson(lesson);
    setIsAIGenerated(false);
    setGenerationNotice(null);
  }, [lesson.id]);

  // Practice state
  const [fillAnswer, setFillAnswer] = useState<string | null>(null);
  const [matchSelectedLeft, setMatchSelectedLeft] = useState<string | null>(null);
  const [matchesFound, setMatchesFound] = useState<string[]>([]);
  const [arrangedWords, setArrangedWords] = useState<string[]>([]);

  // Quiz state
  const [quizIndex, setQuizIndex] = useState<number>(0);
  const [selectedQuizOption, setSelectedQuizOption] = useState<string | null>(null);
  const [quizScore, setQuizScore] = useState<number>(0);
  const [quizAnswered, setQuizAnswered] = useState<boolean>(false);

  // Pronunciation Check Modal state (Web Speech API)
  const [pronounceModal, setPronounceModal] = useState<{
    isOpen: boolean;
    sentence: string;
    reading?: string;
    english?: string;
    hindi?: string;
  }>({
    isOpen: false,
    sentence: "",
  });

  const openPronounceCheck = (
    sentence: string,
    reading?: string,
    english?: string,
    hindi?: string
  ) => {
    setPronounceModal({
      isOpen: true,
      sentence,
      reading,
      english,
      hindi,
    });
  };

  const targetLang = user?.targetLanguage || "Japanese";
  const langMeta = getLanguageMeta(targetLang);

  // Reset progress when module or activeLesson changes
  useEffect(() => {
    setCurrentStep(1);
    setActiveVocabIndex(0);
    setFillAnswer(null);
    setMatchSelectedLeft(null);
    setMatchesFound([]);
    setArrangedWords([]);
    setQuizIndex(0);
    setSelectedQuizOption(null);
    setQuizScore(0);
    setQuizAnswered(false);
  }, [activeLesson.id]);

  const handleGenerateAILesson = async (customTopic?: string) => {
    setIsGeneratingAI(true);
    setGenerationNotice(null);
    try {
      const res = await generateAILesson({
        targetLanguage: targetLang,
        nativeLanguage: user?.nativeLanguage || "English",
        moduleType: selectedModuleId,
        topicTitle: customTopic || activeLesson.title,
        userLevel: user?.level || "Beginner",
        customPrompt: customTopic,
      });
      if (res.success && res.lesson) {
        setActiveLesson(res.lesson);
        setIsAIGenerated(true);
        setCurrentStep(1);
        playChime(true);
        triggerCelebration();
        setGenerationNotice(`✨ Dynamic ${targetLang} curriculum generated by Gemini!`);
        if (showCustomModal) {
          setShowCustomModal(false);
          setCustomTopicInput("");
        }
      } else {
        setGenerationNotice("Active curriculum loaded.");
      }
    } catch (err: any) {
      console.warn("Generation error:", err);
    } finally {
      setIsGeneratingAI(false);
    }
  };

  const stepsList = [
    { num: 1, name: "Scene Intro" },
    { num: 2, name: "Dialogue" },
    { num: 3, name: "Vocabulary" },
    { num: 4, name: "Grammar" },
    { num: 5, name: "Examples" },
    { num: 6, name: "Activities" },
    { num: 7, name: "Mini Quiz" },
    { num: 8, name: "Summary" },
    { num: 9, name: "+XP Reward" },
    { num: 10, name: "Unlocked!" },
  ];

  const triggerCelebration = () => {
    try {
      confetti({
        particleCount: 80,
        spread: 70,
        origin: { y: 0.6 },
        colors: ["#6366f1", "#a855f7", "#ec4899", "#10b981", "#f59e0b"],
      });
    } catch {
      // safe fallback
    }
  };

  const handleNextStep = () => {
    if (currentStep === 8) {
      triggerCelebration();
      playChime(true);
      onCompleteLesson(activeLesson.summary.xpReward);
    }
    if (currentStep < 10) {
      setCurrentStep(currentStep + 1);
    }
  };

  const handleMatchClick = (side: "left" | "right", value: string) => {
    if (side === "left") {
      setMatchSelectedLeft(value);
    } else if (matchSelectedLeft) {
      const pair = activeLesson.practiceActivities.matchPairs.find(
        (p) => p.left === matchSelectedLeft && p.right === value
      );
      if (pair) {
        setMatchesFound([...matchesFound, matchSelectedLeft]);
        playChime(true);
      } else {
        playChime(false);
      }
      setMatchSelectedLeft(null);
    }
  };

  const handleQuizAnswer = (option: string) => {
    if (quizAnswered) return;
    setSelectedQuizOption(option);
    setQuizAnswered(true);

    const isCorrect = option === activeLesson.miniQuiz[quizIndex]?.correctAnswer;
    if (isCorrect) {
      setQuizScore(quizScore + 1);
      playChime(true);
    } else {
      playChime(false);
    }
  };

  const handleNextQuizQuestion = () => {
    if (quizIndex < activeLesson.miniQuiz.length - 1) {
      setQuizIndex(quizIndex + 1);
      setSelectedQuizOption(null);
      setQuizAnswered(false);
    } else {
      handleNextStep();
    }
  };

  const handleSpeak = (text: string) => {
    speakText(text, langMeta.voiceCode);
  };

  const currentWord = activeLesson.vocabulary[activeVocabIndex] || activeLesson.vocabulary[0];

  const getModuleIcon = (id: string) => {
    switch (id) {
      case "airport":
        return <Plane className="w-3.5 h-3.5" />;
      case "hotel":
        return <Building2 className="w-3.5 h-3.5" />;
      case "restaurant":
        return <Utensils className="w-3.5 h-3.5" />;
      case "metro":
        return <Train className="w-3.5 h-3.5" />;
      case "shopping":
        return <ShoppingBag className="w-3.5 h-3.5" />;
      case "attractions":
        return <Landmark className="w-3.5 h-3.5" />;
      default:
        return <BookOpen className="w-3.5 h-3.5" />;
    }
  };

  return (
    <div className="max-w-3xl mx-auto space-y-5 pb-16 animate-in fade-in duration-200">
      {/* Target Language & Module Switcher Strip */}
      <div className="bg-white rounded-3xl p-4 sm:p-5 border border-slate-200/80 shadow-xs space-y-3">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <span className="text-2xl">{langMeta.flag}</span>
            <div>
              <div className="text-xs font-bold text-slate-900 flex items-center gap-1.5">
                <span>{targetLang} Learning Mission</span>
                <span className="px-2 py-0.5 rounded-md bg-indigo-50 text-indigo-700 text-[10px] font-bold">
                  {langMeta.city}, {langMeta.country}
                </span>
                {isAIGenerated && (
                  <span className="px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-800 text-[10px] font-bold border border-emerald-300 flex items-center gap-1">
                    <Sparkles className="w-2.5 h-2.5 text-emerald-600" /> Dynamic AI
                  </span>
                )}
              </div>
              <div className="text-[11px] text-slate-500 font-medium">
                Active Module: <strong className="text-slate-800">{activeLesson.title}</strong> ({activeLesson.location})
              </div>
            </div>
          </div>

          {/* Action buttons: AI Generator, Pronunciation Check & Hindi Toggle */}
          <div className="flex items-center flex-wrap gap-2">
            {/* Dynamic AI Generator button */}
            <button
              onClick={() => handleGenerateAILesson()}
              disabled={isGeneratingAI}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all border bg-gradient-to-r from-indigo-50 to-purple-50 text-indigo-700 border-indigo-200 hover:from-indigo-100 hover:to-purple-100 shadow-2xs disabled:opacity-50"
              title="Generate a dynamic fresh curriculum with AI"
            >
              {isGeneratingAI ? (
                <Loader2 className="w-3.5 h-3.5 text-indigo-600 animate-spin" />
              ) : (
                <Wand2 className="w-3.5 h-3.5 text-indigo-600" />
              )}
              <span>{isGeneratingAI ? "AI Generating..." : "✨ AI Generate"}</span>
            </button>

            {/* Custom situation modal trigger */}
            <button
              onClick={() => setShowCustomModal(true)}
              className="flex items-center gap-1 px-2.5 py-1.5 rounded-xl text-xs font-semibold transition-all border bg-slate-50 text-slate-700 border-slate-200 hover:bg-slate-100"
              title="Generate a lesson on any custom topic or situation"
            >
              <PlusCircle className="w-3.5 h-3.5 text-slate-500" />
              <span>Custom Topic</span>
            </button>

            <button
              onClick={() => {
                const sample =
                  activeLesson.dialogue[0]?.japanese ||
                  activeLesson.vocabulary[0]?.exampleSentence ||
                  activeLesson.vocabulary[0]?.word ||
                  "Hello";
                const reading =
                  activeLesson.dialogue[0]?.romaji || activeLesson.vocabulary[0]?.exampleReading;
                const english =
                  activeLesson.dialogue[0]?.english || activeLesson.vocabulary[0]?.exampleMeaning;
                const hindi =
                  activeLesson.dialogue[0]?.hindi || activeLesson.vocabulary[0]?.exampleHindi;
                openPronounceCheck(sample, reading, english, hindi);
              }}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all border bg-indigo-50 text-indigo-700 border-indigo-200 hover:bg-indigo-100 shadow-2xs"
              title="Test pronunciation using Web Speech API"
            >
              <Mic className="w-3.5 h-3.5 text-indigo-600 animate-pulse" />
              <span>🎙️ Pronounce</span>
            </button>

            {/* Hindi translation toggle */}
            <button
              onClick={() => setShowHindi(!showHindi)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-bold transition-all border ${
                showHindi
                  ? "bg-amber-50 text-amber-900 border-amber-300 shadow-2xs"
                  : "bg-slate-100 text-slate-600 border-slate-200 hover:bg-slate-200"
              }`}
              title="Toggle Hindi meaning on/off"
            >
              <Languages className="w-3.5 h-3.5 text-amber-600" />
              <span>{showHindi ? "🇮🇳 हिंदी ON" : "🇮🇳 हिंदी OFF"}</span>
            </button>
          </div>
        </div>

        {/* AI Generating Indicator Banner */}
        {isGeneratingAI && (
          <div className="p-3 bg-gradient-to-r from-indigo-50 via-purple-50 to-pink-50 border border-indigo-200 rounded-2xl flex items-center gap-2.5 text-xs text-indigo-800 font-medium animate-pulse">
            <Loader2 className="w-4 h-4 text-indigo-600 animate-spin shrink-0" />
            <div>
              <strong>Gemini AI is crafting authentic curriculum:</strong> Generating realistic dialogues, phonetic romanization, travel vocabulary, grammar formulas, exercises & quiz for <strong>{targetLang}</strong>!
            </div>
          </div>
        )}

        {/* Generation Notice */}
        {generationNotice && !isGeneratingAI && (
          <div className="p-2 bg-emerald-50 border border-emerald-200 text-emerald-800 rounded-xl text-[11px] font-medium flex items-center justify-between">
            <span>{generationNotice}</span>
            <button onClick={() => setGenerationNotice(null)} className="text-emerald-600 hover:text-emerald-950 font-bold ml-2">✕</button>
          </div>
        )}

        {/* 6 Module Selector Pills */}
        <div className="pt-2 border-t border-slate-100">
          <div className="text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-2">
            Switch Module (Har module ke alag sentences & vocab):
          </div>
          <div className="grid grid-cols-3 sm:grid-cols-6 gap-1.5">
            {MODULE_DEFINITIONS.map((mod) => {
              const isSelected = selectedModuleId === mod.id || activeLesson.id.includes(mod.id);
              return (
                <button
                  key={mod.id}
                  onClick={() => onSelectModule && onSelectModule(mod.id)}
                  className={`flex flex-col items-center justify-center p-2 rounded-xl text-center transition-all border ${
                    isSelected
                      ? "bg-indigo-600 text-white border-indigo-600 shadow-xs font-bold"
                      : "bg-slate-50 hover:bg-indigo-50/70 hover:border-indigo-200 border-slate-200 text-slate-700 font-medium"
                  }`}
                >
                  <div className="mb-0.5">{getModuleIcon(mod.id)}</div>
                  <span className="text-[11px] leading-tight truncate max-w-full">
                    {mod.name.split(" ")[0]}
                  </span>
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* Custom Topic Modal */}
      {showCustomModal && (
        <div className="fixed inset-0 z-50 bg-slate-900/50 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-3xl p-6 max-w-md w-full shadow-2xl border border-slate-200 animate-in zoom-in-95 duration-200">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-xl bg-indigo-100 text-indigo-700 flex items-center justify-center font-bold">
                  ✨
                </div>
                <div>
                  <h3 className="text-base font-bold text-slate-900">Custom AI Lesson</h3>
                  <p className="text-xs text-slate-500">Generate a complete lesson for any travel situation</p>
                </div>
              </div>
              <button
                onClick={() => setShowCustomModal(false)}
                className="text-slate-400 hover:text-slate-600 p-1 text-lg font-bold"
              >
                ✕
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">
                  What situation do you want to learn in {targetLang}?
                </label>
                <input
                  type="text"
                  value={customTopicInput}
                  onChange={(e) => setCustomTopicInput(e.target.value)}
                  placeholder="e.g., Ordering vegetarian ramen, Renting a scooter, Lost luggage..."
                  className="w-full px-3.5 py-2.5 rounded-xl border border-slate-200 focus:outline-none focus:ring-2 focus:ring-indigo-500 text-sm text-slate-800"
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && customTopicInput.trim()) {
                      handleGenerateAILesson(customTopicInput.trim());
                    }
                  }}
                />
              </div>

              <div className="flex flex-wrap gap-1.5">
                <span className="text-[11px] text-slate-400 font-medium">Quick ideas:</span>
                {[
                  "Ordering Street Food",
                  "Pharmacy & Medicine",
                  "Asking Directions to Metro",
                  "Booking a Sightseeing Tour",
                ].map((idea) => (
                  <button
                    key={idea}
                    onClick={() => setCustomTopicInput(idea)}
                    className="text-[11px] px-2.5 py-1 rounded-lg bg-slate-100 hover:bg-indigo-50 text-slate-700 hover:text-indigo-700 border border-slate-200 transition-colors"
                  >
                    {idea}
                  </button>
                ))}
              </div>

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  onClick={() => setShowCustomModal(false)}
                  className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-600 hover:bg-slate-100"
                >
                  Cancel
                </button>
                <button
                  onClick={() => handleGenerateAILesson(customTopicInput.trim())}
                  disabled={!customTopicInput.trim() || isGeneratingAI}
                  className="px-4 py-2 rounded-xl text-xs font-bold bg-indigo-600 hover:bg-indigo-700 text-white shadow-xs disabled:opacity-50 flex items-center gap-1.5"
                >
                  {isGeneratingAI ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
                  <span>Generate with Gemini</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 10-Step Breadcrumb Bar */}
      <div className="bg-white rounded-2xl p-4 border border-slate-200/80 shadow-xs">
        <div className="flex items-center justify-between text-xs mb-2">
          <div className="font-bold text-slate-800">
            Step {currentStep} of 10:{" "}
            <span className="text-indigo-600 font-semibold">{stepsList[currentStep - 1].name}</span>
          </div>
          <span className="text-slate-500 font-medium text-[11px] flex items-center gap-1">
            <span>{langMeta.flag}</span>
            <span>{activeLesson.location}</span>
          </span>
        </div>

        {/* Stepper Dots / Bars */}
        <div className="grid grid-cols-10 gap-1.5">
          {stepsList.map((st) => {
            const isPassed = st.num < currentStep;
            const isCurrent = st.num === currentStep;
            return (
              <div
                key={st.num}
                onClick={() => {
                  if (st.num <= currentStep) setCurrentStep(st.num);
                }}
                className={`h-2 rounded-full cursor-pointer transition-all duration-300 ${
                  isPassed
                    ? "bg-emerald-500"
                    : isCurrent
                    ? "bg-indigo-600 ring-2 ring-indigo-400/40"
                    : "bg-slate-200"
                }`}
                title={`Step ${st.num}: ${st.name}`}
              />
            );
          })}
        </div>
      </div>

      {/* STEP 1: Lesson Introduction (Real-Life Scene) */}
      {currentStep === 1 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/80 shadow-sm space-y-6 text-center">
          <div className="relative overflow-hidden rounded-2xl bg-gradient-to-tr from-indigo-900 via-indigo-800 to-slate-900 text-white p-8">
            <div className="text-5xl mb-3">{langMeta.flag}</div>
            <h2 className="text-2xl sm:text-3xl font-black tracking-tight">
              {activeLesson.sceneIntro.title}
            </h2>
            <p className="text-indigo-200 font-semibold text-sm mt-1">
              {targetLang} • {activeLesson.location}
            </p>
            <p className="text-xs text-indigo-100/90 max-w-md mx-auto mt-3 leading-relaxed">
              {activeLesson.sceneIntro.description}
            </p>
          </div>

          <div className="text-left space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">
              What you will accomplish in this mission:
            </h4>
            <div className="space-y-2">
              {activeLesson.sceneIntro.highlights.map((h, i) => (
                <div
                  key={i}
                  className="flex items-center gap-2.5 p-3 rounded-xl bg-indigo-50/60 border border-indigo-100 text-xs text-indigo-950 font-medium"
                >
                  <CheckCircle className="w-4 h-4 text-indigo-600 shrink-0" />
                  {h}
                </div>
              ))}
            </div>
          </div>

          <button
            onClick={handleNextStep}
            className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-2xl shadow-md shadow-indigo-100 flex items-center justify-center gap-2 text-sm transition-all"
          >
            Start Lesson Flow (Dialogue)
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* STEP 2: Conversation / Dialogue */}
      {currentStep === 2 && (
        <div className="bg-white rounded-3xl p-6 border border-slate-200/80 shadow-sm space-y-6">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div>
              <h3 className="text-base font-bold text-slate-900">
                {activeLesson.title} — Real-world Dialogue
              </h3>
              <p className="text-xs text-slate-500">
                Tap the speaker button to hear native {targetLang} pronunciation
              </p>
            </div>
            <button
              onClick={() => {
                const allLines = activeLesson.dialogue.map((d) => d.japanese).join(". ");
                handleSpeak(allLines);
              }}
              className="text-xs font-semibold text-indigo-600 bg-indigo-50 px-3 py-1.5 rounded-xl hover:bg-indigo-100 flex items-center gap-1.5 transition-colors"
            >
              <Volume2 className="w-3.5 h-3.5" />
              Listen to All
            </button>
          </div>

          <div className="space-y-3.5">
            {activeLesson.dialogue.map((line) => {
              const isUser = line.role === "user";
              return (
                <div
                  key={line.id}
                  className={`flex gap-3 ${isUser ? "flex-row-reverse" : "flex-row"}`}
                >
                  <div className="w-10 h-10 rounded-2xl bg-slate-100 flex items-center justify-center text-xl shrink-0 shadow-2xs">
                    {line.avatar}
                  </div>
                  <div
                    className={`max-w-[85%] p-4 rounded-2xl space-y-1.5 text-xs ${
                      isUser
                        ? "bg-indigo-600 text-white rounded-tr-xs"
                        : "bg-slate-100 text-slate-900 rounded-tl-xs"
                    }`}
                  >
                    <div className="flex items-center justify-between gap-2">
                      <span
                        className={`text-[10px] font-bold ${
                          isUser ? "text-indigo-200" : "text-slate-500"
                        }`}
                      >
                        {line.speaker}
                      </span>
                      <div className="flex items-center gap-1">
                        <button
                          onClick={() => handleSpeak(line.japanese)}
                          className={`p-1 rounded-full transition-colors ${
                            isUser
                              ? "hover:bg-indigo-500 text-white"
                              : "hover:bg-slate-200 text-slate-600"
                          }`}
                          title="Listen Native Audio"
                        >
                          <Volume2 className="w-3.5 h-3.5" />
                        </button>
                        <button
                          onClick={() =>
                            openPronounceCheck(
                              line.japanese,
                              line.romaji,
                              line.english,
                              line.hindi
                            )
                          }
                          className={`px-2 py-0.5 rounded-lg text-[10px] font-bold flex items-center gap-1 transition-all ${
                            isUser
                              ? "bg-indigo-500/80 hover:bg-indigo-400 text-white"
                              : "bg-white hover:bg-indigo-50 text-indigo-700 border border-slate-200 shadow-2xs"
                          }`}
                          title="Check pronunciation with Web Speech API"
                        >
                          <Mic className="w-3 h-3" />
                          <span>Speak</span>
                        </button>
                      </div>
                    </div>

                    <div className="text-sm sm:text-base font-bold tracking-wide">
                      {line.japanese}
                    </div>

                    {line.romaji && (
                      <div
                        className={`text-[11px] font-mono ${
                          isUser ? "text-indigo-200" : "text-slate-500"
                        }`}
                      >
                        {line.romaji}
                      </div>
                    )}

                    <div
                      className={`pt-1 border-t text-[11px] ${
                        isUser ? "border-indigo-500/40 text-indigo-100" : "border-slate-200 text-slate-700"
                      }`}
                    >
                      {line.english}
                    </div>

                    {/* Optional Hindi translation */}
                    {showHindi && line.hindi && (
                      <div
                        className={`text-[11px] font-semibold pt-0.5 ${
                          isUser ? "text-amber-200" : "text-amber-800"
                        }`}
                      >
                        🇮🇳 {line.hindi}
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          <button
            onClick={handleNextStep}
            className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-2xl shadow-md shadow-indigo-100 flex items-center justify-center gap-2 text-sm transition-all"
          >
            Continue to Vocabulary (3/10)
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* STEP 3: Vocabulary Drill */}
      {currentStep === 3 && (
        <div className="bg-white rounded-3xl p-6 border border-slate-200/80 shadow-sm space-y-6">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-base font-bold text-slate-900">
                Key Vocabulary ({targetLang})
              </h3>
              <p className="text-xs text-slate-500">
                Word {activeVocabIndex + 1} of {activeLesson.vocabulary.length}
              </p>
            </div>
            {/* Quick Word switcher */}
            <div className="flex gap-1.5">
              {activeLesson.vocabulary.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setActiveVocabIndex(i)}
                  className={`w-7 h-7 rounded-lg text-xs font-bold transition-all ${
                    activeVocabIndex === i
                      ? "bg-indigo-600 text-white shadow-xs"
                      : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                  }`}
                >
                  {i + 1}
                </button>
              ))}
            </div>
          </div>

          {/* Word Card */}
          <div className="p-6 sm:p-8 rounded-2xl bg-gradient-to-b from-slate-50 to-white border border-slate-200 text-center space-y-4">
            <div className="inline-block px-2.5 py-1 bg-indigo-50 text-indigo-700 rounded-full text-[11px] font-bold">
              {currentWord.partOfSpeech}
            </div>

            <div className="flex items-center justify-center gap-3">
              <span className="text-3xl sm:text-5xl font-black text-slate-900">
                {currentWord.word}
              </span>
              <button
                onClick={() => handleSpeak(currentWord.word)}
                className="w-10 h-10 rounded-full bg-indigo-100 hover:bg-indigo-200 text-indigo-700 flex items-center justify-center transition-colors"
                title="Play Audio"
              >
                <Volume2 className="w-5 h-5" />
              </button>
              <button
                onClick={() =>
                  openPronounceCheck(
                    currentWord.word,
                    currentWord.reading,
                    currentWord.meaning,
                    currentWord.hindiMeaning
                  )
                }
                className="px-3 py-2 rounded-xl bg-indigo-50 hover:bg-indigo-100 text-indigo-700 border border-indigo-200 flex items-center gap-1.5 text-xs font-bold shadow-2xs"
                title="Pronounce this word with Web Speech API"
              >
                <Mic className="w-4 h-4 text-indigo-600" />
                <span>Pronounce</span>
              </button>
            </div>

            <div className="text-sm font-mono font-medium text-slate-500">{currentWord.reading}</div>
            <div className="text-xl font-bold text-indigo-900">{currentWord.meaning}</div>

            {showHindi && currentWord.hindiMeaning && (
              <div className="text-sm font-semibold text-amber-700 bg-amber-50/70 py-1.5 px-3 rounded-xl border border-amber-200 inline-block">
                🇮🇳 हिंदी अर्थ: {currentWord.hindiMeaning}
              </div>
            )}

            {/* Example sentence */}
            <div className="mt-4 p-4 rounded-xl bg-slate-100/70 border border-slate-200/80 text-left space-y-1">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-bold uppercase text-slate-400">Example in Context</span>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => handleSpeak(currentWord.exampleSentence)}
                    className="text-xs text-indigo-600 hover:text-indigo-800 flex items-center gap-1 font-semibold"
                  >
                    <Volume2 className="w-3.5 h-3.5" />
                    Listen
                  </button>
                  <button
                    onClick={() =>
                      openPronounceCheck(
                        currentWord.exampleSentence,
                        currentWord.exampleReading,
                        currentWord.exampleMeaning,
                        currentWord.exampleHindi
                      )
                    }
                    className="text-xs bg-indigo-50 hover:bg-indigo-100 text-indigo-700 px-2 py-0.5 rounded-lg border border-indigo-200 flex items-center gap-1 font-bold shadow-2xs"
                  >
                    <Mic className="w-3 h-3 text-indigo-600" />
                    Pronounce Check
                  </button>
                </div>
              </div>
              <div className="text-sm font-bold text-slate-800">{currentWord.exampleSentence}</div>
              <div className="text-xs text-slate-500 font-mono">{currentWord.exampleReading}</div>
              <div className="text-xs text-slate-600 italic">{currentWord.exampleMeaning}</div>
              {showHindi && currentWord.exampleHindi && (
                <div className="text-xs text-amber-800 font-medium">🇮🇳 {currentWord.exampleHindi}</div>
              )}
            </div>

            {currentWord.tip && (
              <div className="text-left text-xs text-indigo-900 bg-indigo-50/50 p-3 rounded-xl border border-indigo-100">
                <strong>Traveler Tip:</strong> {currentWord.tip}
              </div>
            )}
          </div>

          <div className="flex items-center justify-between gap-3">
            <button
              onClick={() => setActiveVocabIndex(Math.max(0, activeVocabIndex - 1))}
              disabled={activeVocabIndex === 0}
              className="px-4 py-2.5 rounded-xl border border-slate-200 text-xs font-bold text-slate-600 disabled:opacity-40"
            >
              Previous Word
            </button>
            {activeVocabIndex < activeLesson.vocabulary.length - 1 ? (
              <button
                onClick={() => setActiveVocabIndex(activeVocabIndex + 1)}
                className="px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl text-xs flex items-center gap-1.5"
              >
                Next Word
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            ) : (
              <button
                onClick={handleNextStep}
                className="px-5 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-xl text-xs flex items-center gap-1.5"
              >
                Continue to Grammar (4/10)
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            )}
          </div>
        </div>
      )}

      {/* STEP 4: Grammar in Context */}
      {currentStep === 4 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/80 shadow-sm space-y-6">
          <div>
            <span className="text-xs font-bold uppercase tracking-wider text-indigo-600 bg-indigo-50 px-2.5 py-1 rounded-full">
              Grammar Point ({targetLang})
            </span>
            <h3 className="text-xl font-black text-slate-900 mt-2">{activeLesson.grammar.title}</h3>
            <p className="text-xs text-slate-600 mt-1 leading-relaxed">
              {activeLesson.grammar.explanation}
            </p>
            {showHindi && activeLesson.grammar.hindiExplanation && (
              <div className="mt-2 p-2.5 rounded-xl bg-amber-50 border border-amber-200 text-xs text-amber-900 font-medium">
                🇮🇳 {activeLesson.grammar.hindiExplanation}
              </div>
            )}
          </div>

          {/* Formula / Structure */}
          <div className="p-4 rounded-2xl bg-indigo-50/70 border border-indigo-200 text-center">
            <div className="text-[10px] font-bold uppercase text-indigo-600">Grammar Formula</div>
            <div className="text-base font-black text-indigo-950 mt-1 font-mono">
              {activeLesson.grammar.pattern}
            </div>
            <div className="text-xs text-indigo-700 mt-1">{activeLesson.grammar.structure}</div>
          </div>

          {/* Examples */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold text-slate-700 uppercase tracking-wider">
              Real Situations in {activeLesson.location}:
            </h4>
            {activeLesson.grammar.examples.map((ex, i) => (
              <div
                key={i}
                className="p-3.5 rounded-xl bg-slate-50 border border-slate-200/80 flex items-center justify-between"
              >
                <div>
                  <div className="font-bold text-slate-900 text-xs sm:text-sm">{ex.japanese}</div>
                  <div className="text-[11px] text-slate-500 font-mono">{ex.romaji}</div>
                  <div className="text-xs text-indigo-700 mt-0.5">{ex.english}</div>
                  {showHindi && ex.hindi && (
                    <div className="text-xs text-amber-800 mt-0.5">🇮🇳 {ex.hindi}</div>
                  )}
                </div>
                <button
                  onClick={() => handleSpeak(ex.japanese)}
                  className="p-2 rounded-xl bg-white border border-slate-200 hover:bg-slate-100 text-indigo-600 transition-colors"
                >
                  <Volume2 className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>

          <button
            onClick={handleNextStep}
            className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-2xl shadow-md shadow-indigo-100 flex items-center justify-center gap-2 text-sm transition-all"
          >
            Continue to Example Sentences (5/10)
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* STEP 5: Example Sentences Practice (Dynamic per module) */}
      {currentStep === 5 && (
        <div className="bg-white rounded-3xl p-6 border border-slate-200/80 shadow-sm space-y-6">
          <div>
            <h3 className="text-base font-bold text-slate-900">
              Module Example Sentences ({activeLesson.location})
            </h3>
            <p className="text-xs text-slate-500">
              Listen and repeat each phrase aloud to build spontaneous muscle memory.
            </p>
          </div>

          <div className="space-y-3">
            {activeLesson.vocabulary.slice(0, 4).map((voc, i) => (
              <div
                key={i}
                className="p-4 rounded-2xl bg-gradient-to-r from-slate-50 to-indigo-50/30 border border-slate-200 flex flex-col sm:flex-row sm:items-center justify-between gap-3"
              >
                <div className="space-y-1">
                  <span className="text-[10px] font-bold uppercase bg-white border border-slate-200 px-2 py-0.5 rounded text-indigo-600">
                    Pattern {i + 1}: {voc.word}
                  </span>
                  <div className="text-sm font-bold text-slate-900 pt-1">{voc.exampleSentence}</div>
                  <div className="text-xs font-mono text-slate-500">{voc.exampleReading}</div>
                  <div className="text-xs text-slate-700 font-medium">{voc.exampleMeaning}</div>
                  {showHindi && voc.hindiMeaning && (
                    <div className="text-xs text-amber-800 font-semibold">
                      🇮🇳 अर्थ: {voc.hindiMeaning}
                    </div>
                  )}
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <button
                    onClick={() => handleSpeak(voc.exampleSentence)}
                    className="w-10 h-10 rounded-2xl bg-slate-100 hover:bg-slate-200 text-slate-700 flex items-center justify-center shadow-xs transition-colors"
                    title="Listen Native Audio"
                  >
                    <Volume2 className="w-4 h-4" />
                  </button>
                  <button
                    onClick={() =>
                      openPronounceCheck(
                        voc.exampleSentence,
                        voc.exampleReading,
                        voc.exampleMeaning,
                        voc.exampleHindi || voc.hindiMeaning
                      )
                    }
                    className="px-3.5 py-2.5 rounded-2xl bg-indigo-600 hover:bg-indigo-700 text-white flex items-center gap-1.5 shadow-xs text-xs font-bold transition-colors"
                    title="Check Pronunciation with Web Speech API"
                  >
                    <Mic className="w-3.5 h-3.5" />
                    <span>Pronounce Check</span>
                  </button>
                </div>
              </div>
            ))}
          </div>

          <button
            onClick={handleNextStep}
            className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-2xl shadow-md shadow-indigo-100 flex items-center justify-center gap-2 text-sm transition-all"
          >
            Start Practice Activities (6/10)
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* STEP 6: Practice Activities */}
      {currentStep === 6 && (
        <div className="bg-white rounded-3xl p-6 border border-slate-200/80 shadow-sm space-y-6">
          <div>
            <h3 className="text-base font-bold text-slate-900">
              Interactive Practice Drills ({targetLang})
            </h3>
            <p className="text-xs text-slate-500">
              Complete the drills for this module to lock in retention.
            </p>
          </div>

          {/* Activity 1: Fill in the blank */}
          <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-3">
            <div className="text-xs font-bold uppercase text-indigo-700">
              Activity 1: Fill in the Blank
            </div>
            <div className="text-sm font-bold text-slate-900">
              {activeLesson.practiceActivities.fillInTheBlank.sentence}
            </div>

            <div className="grid grid-cols-2 gap-2 pt-1">
              {activeLesson.practiceActivities.fillInTheBlank.options.map((opt) => {
                const isSelected = fillAnswer === opt;
                const isCorrect = opt === activeLesson.practiceActivities.fillInTheBlank.missingWord;
                return (
                  <button
                    key={opt}
                    onClick={() => {
                      setFillAnswer(opt);
                      if (isCorrect) playChime(true);
                      else playChime(false);
                    }}
                    className={`p-2.5 rounded-xl border text-xs font-bold transition-all ${
                      isSelected
                        ? isCorrect
                          ? "bg-emerald-50 border-emerald-500 text-emerald-800"
                          : "bg-rose-50 border-rose-400 text-rose-800"
                        : "bg-white border-slate-200 hover:border-slate-300 text-slate-800"
                    }`}
                  >
                    {opt}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Activity 2: Match Pairs */}
          <div className="p-5 rounded-2xl bg-slate-50 border border-slate-200 space-y-3">
            <div className="text-xs font-bold uppercase text-indigo-700">
              Activity 2: Match the Pairs
            </div>
            <p className="text-xs text-slate-500">
              Select a {targetLang} word on the left, then click its meaning on the right.
            </p>

            <div className="grid grid-cols-2 gap-4 pt-1">
              {/* Left column */}
              <div className="space-y-2">
                {activeLesson.practiceActivities.matchPairs.map((p) => {
                  const isDone = matchesFound.includes(p.left);
                  const isSelected = matchSelectedLeft === p.left;
                  return (
                    <button
                      key={p.left}
                      disabled={isDone}
                      onClick={() => handleMatchClick("left", p.left)}
                      className={`w-full p-2.5 rounded-xl border text-xs font-bold text-left transition-all ${
                        isDone
                          ? "bg-emerald-50 border-emerald-300 text-emerald-700 opacity-60"
                          : isSelected
                          ? "bg-indigo-600 text-white border-indigo-600"
                          : "bg-white border-slate-200 text-slate-800 hover:border-indigo-300"
                      }`}
                    >
                      {p.left}
                      {isDone && <Check className="w-3.5 h-3.5 inline ml-1.5" />}
                    </button>
                  );
                })}
              </div>

              {/* Right column */}
              <div className="space-y-2">
                {activeLesson.practiceActivities.matchPairs
                  .slice()
                  .reverse()
                  .map((p) => {
                    const isDone = matchesFound.includes(p.left);
                    return (
                      <button
                        key={p.right}
                        disabled={isDone}
                        onClick={() => handleMatchClick("right", p.right)}
                        className={`w-full p-2.5 rounded-xl border text-xs font-bold text-left transition-all ${
                          isDone
                            ? "bg-emerald-50 border-emerald-300 text-emerald-700 opacity-60"
                            : "bg-white border-slate-200 text-slate-800 hover:border-indigo-400"
                        }`}
                      >
                        {p.right}
                      </button>
                    );
                  })}
              </div>
            </div>
          </div>

          {/* Activity 3: Spoken Pronunciation Challenge */}
          <div className="p-5 rounded-2xl bg-gradient-to-r from-indigo-50/70 via-purple-50/50 to-indigo-50/70 border border-indigo-200 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase text-indigo-700 flex items-center gap-1.5">
                <Mic className="w-4 h-4 text-indigo-600 animate-pulse" />
                Activity 3: Spoken Pronunciation Challenge
              </span>
              <span className="text-[10px] font-extrabold px-2.5 py-0.5 rounded-md bg-indigo-600 text-white shadow-2xs">
                Web Speech API
              </span>
            </div>
            <p className="text-xs text-slate-600">
              Speak this key mission sentence aloud in {targetLang}. The Web Speech API compares your spoken phonetics and word match in real-time!
            </p>

            <div className="p-4 rounded-2xl bg-white border border-indigo-100 shadow-2xs space-y-2 text-center">
              <div className="text-lg sm:text-xl font-black text-slate-900 tracking-wide">
                {activeLesson.dialogue[0]?.japanese || activeLesson.vocabulary[0]?.exampleSentence}
              </div>
              <div className="text-xs font-mono text-slate-500">
                {activeLesson.dialogue[0]?.romaji || activeLesson.vocabulary[0]?.exampleReading}
              </div>
              <div className="text-xs font-semibold text-indigo-900">
                "{activeLesson.dialogue[0]?.english || activeLesson.vocabulary[0]?.exampleMeaning}"
              </div>
              {showHindi && (activeLesson.dialogue[0]?.hindi || activeLesson.vocabulary[0]?.exampleHindi) && (
                <div className="text-xs font-bold text-amber-800">
                  🇮🇳 {activeLesson.dialogue[0]?.hindi || activeLesson.vocabulary[0]?.exampleHindi}
                </div>
              )}

              <div className="pt-2 flex justify-center gap-2">
                <button
                  onClick={() =>
                    handleSpeak(
                      activeLesson.dialogue[0]?.japanese || activeLesson.vocabulary[0]?.exampleSentence
                    )
                  }
                  className="px-3.5 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold flex items-center gap-1.5 transition-colors"
                  title="Listen Native Audio"
                >
                  <Volume2 className="w-3.5 h-3.5 text-indigo-600" />
                  Listen Audio
                </button>
                <button
                  onClick={() => {
                    const phrase =
                      activeLesson.dialogue[0]?.japanese || activeLesson.vocabulary[0]?.exampleSentence;
                    const reading =
                      activeLesson.dialogue[0]?.romaji || activeLesson.vocabulary[0]?.exampleReading;
                    const english =
                      activeLesson.dialogue[0]?.english || activeLesson.vocabulary[0]?.exampleMeaning;
                    const hindi =
                      activeLesson.dialogue[0]?.hindi || activeLesson.vocabulary[0]?.exampleHindi;
                    openPronounceCheck(phrase, reading, english, hindi);
                  }}
                  className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold flex items-center gap-1.5 shadow-xs transition-all"
                  title="Check Pronunciation with Web Speech API"
                >
                  <Mic className="w-3.5 h-3.5 animate-pulse" />
                  Speak & Check Pronunciation
                </button>
              </div>
            </div>
          </div>

          <button
            onClick={handleNextStep}
            className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-2xl shadow-md shadow-indigo-100 flex items-center justify-center gap-2 text-sm transition-all"
          >
            Continue to Mini Quiz (7/10)
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* STEP 7: Mini Quiz */}
      {currentStep === 7 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/80 shadow-sm space-y-6">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <div>
              <span className="text-xs font-bold uppercase tracking-wider text-indigo-600">
                Question {quizIndex + 1} of {activeLesson.miniQuiz.length}
              </span>
              <h3 className="text-base font-bold text-slate-900 mt-1">
                {activeLesson.miniQuiz[quizIndex]?.prompt}
              </h3>
              {showHindi && activeLesson.miniQuiz[quizIndex]?.hindiPrompt && (
                <p className="text-xs text-amber-800 font-medium mt-0.5">
                  🇮🇳 {activeLesson.miniQuiz[quizIndex]?.hindiPrompt}
                </p>
              )}
            </div>
            <div className="text-xs font-bold bg-indigo-50 text-indigo-700 px-3 py-1 rounded-full">
              Score: {quizScore}
            </div>
          </div>

          {/* Options */}
          <div className="space-y-2.5">
            {activeLesson.miniQuiz[quizIndex]?.options.map((opt) => {
              const isSelected = selectedQuizOption === opt;
              const isCorrect = opt === activeLesson.miniQuiz[quizIndex]?.correctAnswer;
              return (
                <button
                  key={opt}
                  disabled={quizAnswered}
                  onClick={() => handleQuizAnswer(opt)}
                  className={`w-full p-4 rounded-2xl border text-left text-xs sm:text-sm font-semibold flex items-center justify-between transition-all ${
                    quizAnswered
                      ? isCorrect
                        ? "bg-emerald-50 border-emerald-500 text-emerald-900 font-bold"
                        : isSelected
                        ? "bg-rose-50 border-rose-400 text-rose-900"
                        : "bg-slate-50 border-slate-200 text-slate-500"
                      : "bg-white border-slate-200 hover:border-indigo-400 text-slate-800"
                  }`}
                >
                  <span>{opt}</span>
                  {quizAnswered && isCorrect && (
                    <CheckCircle className="w-4 h-4 text-emerald-600" />
                  )}
                  {quizAnswered && isSelected && !isCorrect && (
                    <XCircle className="w-4 h-4 text-rose-500" />
                  )}
                </button>
              );
            })}
          </div>

          {quizAnswered && (
            <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200 text-xs text-slate-700 space-y-1">
              <div className="font-bold text-slate-900">Explanation:</div>
              <div>{activeLesson.miniQuiz[quizIndex]?.explanation}</div>
            </div>
          )}

          {quizAnswered && (
            <button
              onClick={handleNextQuizQuestion}
              className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-2xl shadow-md shadow-indigo-100 flex items-center justify-center gap-2 text-sm transition-all"
            >
              {quizIndex < activeLesson.miniQuiz.length - 1 ? "Next Question" : "See Lesson Summary (8/10)"}
              <ArrowRight className="w-4 h-4" />
            </button>
          )}
        </div>
      )}

      {/* STEP 8: Lesson Summary */}
      {currentStep === 8 && (
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/80 shadow-sm text-center space-y-6">
          <div className="w-20 h-20 rounded-3xl bg-gradient-to-tr from-indigo-500 to-purple-600 text-white flex items-center justify-center text-4xl mx-auto shadow-lg shadow-indigo-100">
            🌟
          </div>

          <div>
            <h2 className="text-2xl font-black text-slate-900">Great Job!</h2>
            <p className="text-xs text-slate-500 mt-1">
              You completed <span className="font-bold text-indigo-600">{activeLesson.title}</span> in {targetLang}
            </p>
          </div>

          {/* 4 Summary Stats */}
          <div className="grid grid-cols-2 gap-3 max-w-sm mx-auto text-left text-xs">
            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <div className="text-slate-500">Vocabulary</div>
              <div className="text-base font-black text-slate-900">
                +{activeLesson.summary.newWordsCount} Words
              </div>
            </div>
            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <div className="text-slate-500">Grammar Point</div>
              <div className="text-base font-black text-slate-900">
                {activeLesson.summary.grammarPointsCount} Mastered
              </div>
            </div>
            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <div className="text-slate-500">Activities</div>
              <div className="text-base font-black text-slate-900">
                {activeLesson.summary.activitiesCompleted} Completed
              </div>
            </div>
            <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
              <div className="text-slate-500">Quiz Score</div>
              <div className="text-base font-black text-emerald-600">
                {quizScore}/{activeLesson.miniQuiz.length} Correct
              </div>
            </div>
          </div>

          <button
            onClick={handleNextStep}
            className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-2xl shadow-md shadow-indigo-100 flex items-center justify-center gap-2 text-sm transition-all"
          >
            Awesome! Claim XP Reward (9/10)
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* STEP 9: Progress Updated (+XP Reward) */}
      {currentStep === 9 && (
        <div className="bg-white rounded-3xl p-8 border border-slate-200/80 shadow-sm text-center space-y-6">
          <div className="relative inline-block">
            <div className="w-28 h-28 rounded-full bg-gradient-to-tr from-amber-400 to-orange-500 text-white flex flex-col items-center justify-center mx-auto shadow-xl shadow-amber-200/60 animate-bounce">
              <span className="text-xs font-bold uppercase tracking-wider text-amber-100">Reward</span>
              <span className="text-3xl font-black">+{activeLesson.summary.xpReward}</span>
              <span className="text-[10px] font-bold text-amber-100">XP</span>
            </div>
          </div>

          <div>
            <h2 className="text-2xl font-black text-slate-900">Your Progress Has Been Updated!</h2>
            <p className="text-xs text-slate-500 mt-1">
              Consistent daily practice creates real-world fluency.
            </p>
          </div>

          <div className="max-w-xs mx-auto p-4 rounded-2xl bg-slate-50 border border-slate-200 text-xs space-y-2 text-left">
            <div className="flex justify-between font-medium">
              <span className="text-slate-600">Current XP:</span>
              <span className="font-bold text-indigo-700">{(user?.xp || 1200) + activeLesson.summary.xpReward} XP</span>
            </div>
            <div className="flex justify-between font-medium">
              <span className="text-slate-600">Day Streak:</span>
              <span className="font-bold text-amber-600">{user?.streakDays || 7} Days 🔥</span>
            </div>
            <div className="flex justify-between font-medium">
              <span className="text-slate-600">Target Language:</span>
              <span className="font-bold text-emerald-600">{langMeta.flag} {targetLang}</span>
            </div>
          </div>

          <button
            onClick={handleNextStep}
            className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-2xl shadow-md shadow-indigo-100 flex items-center justify-center gap-2 text-sm transition-all"
          >
            Check Destination Unlocks (10/10)
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      )}

      {/* STEP 10: Next Location Unlocked */}
      {currentStep === 10 && (
        <div className="bg-white rounded-3xl p-8 border border-slate-200/80 shadow-sm text-center space-y-6">
          <div className="w-20 h-20 rounded-3xl bg-gradient-to-tr from-emerald-500 to-teal-600 text-white flex items-center justify-center text-3xl mx-auto shadow-lg shadow-emerald-100">
            <Unlock className="w-10 h-10" />
          </div>

          <div>
            <span className="text-xs font-bold uppercase tracking-wider text-emerald-600 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-200">
              Milestone Accomplished
            </span>
            <h2 className="text-2xl font-black text-slate-900 mt-2">Congratulations!</h2>
            <p className="text-xs text-slate-500 mt-1 max-w-sm mx-auto">
              You mastered the <strong>{activeLesson.title}</strong> module in <strong>{targetLang}</strong>!
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-3 pt-2">
            <button
              onClick={onGoToDashboard}
              className="flex-1 py-3.5 bg-slate-100 hover:bg-slate-200 text-slate-800 font-bold rounded-2xl text-xs transition-colors"
            >
              Return to Dashboard
            </button>
            <button
              onClick={() => {
                setCurrentStep(1);
                setActiveVocabIndex(0);
                setFillAnswer(null);
                setQuizAnswered(false);
                setQuizIndex(0);
              }}
              className="flex-1 py-3.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-2xl shadow-md text-xs transition-all flex items-center justify-center gap-1.5"
            >
              Practice Lesson Again
              <RotateCcw className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>
      )}
      {/* Pronunciation Check Modal powered by Web Speech API */}
      <PronunciationCheckModal
        isOpen={pronounceModal.isOpen}
        onClose={() => setPronounceModal({ ...pronounceModal, isOpen: false })}
        targetSentence={pronounceModal.sentence}
        targetReading={pronounceModal.reading}
        englishTranslation={pronounceModal.english}
        hindiTranslation={pronounceModal.hindi}
        targetLanguage={targetLang}
        voiceCode={langMeta.voiceCode}
        onRecordXP={(xp) => {
          onCompleteLesson(xp);
          triggerCelebration();
        }}
      />
    </div>
  );
};
